### ISSUE TITLE
date-set doesn't consider date-format

### ISSUE THREAD

**Issue by jonataswalker** [720kb/angular-datepicker#152] opened 2016-03-04 03:07 UTC
Hi there,

Same as #126 but with `date-set`. 

See http://plnkr.co/edit/KE4V0vkT47HvcdeLPC7g?p=preview

**Comment by 45kb** [comment] 2016-03-04 07:58
Yes it's a known problem, for the moment you can easily handle that like this: http://plnkr.co/edit/8zQfUV27rvMs8pnAvD7q?p=preview

If you try anything feel free to PR !

Thanks :+1:

**Comment by jonataswalker** [comment] 2016-03-04 10:06
> you can easily handle that

Do you mean that plunker is a workaround?

**Comment by 45kb** [comment] 2016-03-04 10:08
Yes. You can format dates as you need using $filter which is the main filter used inside datepicker.
Soon we will check what's going wrong with date-set and formats.

**Comment by jonataswalker** [comment] 2016-03-04 10:11
Ok, but it's not a workaround to the datepicker, right? Since it is setting a wrong date.

Do you have a tip where to start these modifications?

**Comment by 45kb** [comment] 2016-03-04 10:15
Yes, it's a workaround to pass an already formatted date to the datepicker, the issue is probably here https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js#L192

This is the function that set the date inside the input, seems there is something wrong with dateFormat... but i am not sure at the moment.

**Comment by jonataswalker** [comment] 2016-03-04 10:26
I don't see how your plunker can be a workaround, look, the informed date is `04-12-2016` which means **Dec 04**. When you open the picker it is selected **Apr 12**.

Also you have to set `date-set-hidden="true"` to avoid a lot of (unknown for me) errors.

**Comment by 45kb** [comment] 2016-03-04 10:42
@jonataswalker Ok, but you was referring to date-format, if you meant selected date in calendar, that looks more like a css class not being added...

**Comment by 45kb** [comment] 2016-03-04 10:55
Ok i probably found the problem, is in your code, you are using same scope both for ng-model and date-set, just put ng-model="myDate" it should works.

http://plnkr.co/edit/8zQfUV27rvMs8pnAvD7q?p=preview

Also be sure to include always the latest version of angular and angular-socialshare.

Just tell me if it is ok and we close the issue :+1:

**Comment by jonataswalker** [comment] 2016-03-04 11:17
My guess is that we have to parse the date based on `date-format` and then create a right [`new Date(newValue)`](https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js#L327)

**Comment by jonataswalker** [comment] 2016-03-04 11:21
> Just tell me if it is ok and we close the issue

I'm afraid we're not talking about the same thing. I must set a right date on datepicker.

This line `$scope.date = $filter('date')('04-12-2016', 'dd-MM-yyyy');` should set Dec 04, but it's Apr 12 selected.

**Comment by 45kb** [comment] 2016-03-04 11:25
Ofc, but you have to set the format and the date correctly, my bad there.

http://plnkr.co/edit/8zQfUV27rvMs8pnAvD7q

**Comment by 45kb** [comment] 2016-03-04 11:28
As for this https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js#L327, yes i guess, actually, there could be problems there, have you already tried that changing the date-set dynamically?

**Comment by jonataswalker** [comment] 2016-03-04 11:35
This format `04-12-2016` (`dd-MM-YYYY`) is coming from JSON file so I wouldn't like to change to `12-04-2016`. I'd have to create another scope ngModel (well, maybe I'll have to).

Do we have any capability to parse a date based on a format, say, `dd-MM-YYYY`, and create a **date object**?

**Comment by jonataswalker** [comment] 2016-03-04 11:36
> have you already tried that changing the date-set dynamically?

Yes, I use it dynamically.

**Comment by 45kb** [comment] 2016-03-04 11:38
Ok understood, yes you can format with `new Date($filter('date')(jsonDate, 'MM-DD-YYY'));` but you can do this before passing it to the datepicker i mean, in your controller... 

Let me know ... :)

**Comment by jonataswalker** [comment] 2016-03-04 11:40
I've meant parse and set here https://github.com/720kb/angular-datepicker/blob/master/src/js/angular-datepicker.js#L327

**Comment by 45kb** [comment] 2016-03-04 11:42
Yes, unfortunately, i am unable to make tests atm, but i really think there should be no problems making the changes there.

**Closed** 2016-03-17 08:31 UTC
Labels: enhancement

**Comment by 45kb** [comment] 2016-03-17 08:32
@jonataswalker Try updating your module if you want :)

**Comment by jonataswalker** [comment] 2016-03-19 19:30
I'll let you know, many thanks and sorry the lack of activity.
