### ISSUE TITLE
Problem about Date format

### ISSUE THREAD

**Issue by FadiNouh1** [720kb/angular-datepicker#261] opened 2017-04-21 16:18 UTC
I think there is a bug when using the the format of Austrian Calendar
I mean when I put the date format as ("dd.MM.yyyy") , the datepicker opens with flipping between the day and the month ,
ex : 03.04.2017 is initiated in the calendar as 4th of March , not as 3rd of April 
is there solution for this issue?

**Comment by PizzaPete** [comment] 2017-04-24 20:31
Duplicate of #254

**Comment by 45kb** [comment] 2017-05-05 06:54
https://github.com/720kb/angular-datepicker/pull/257

**Closed by 45kb** 2017-05-05 06:54 UTC
