### ISSUE TITLE
unable to use a format other than yyyy-MM-dd (using jquery)

### ISSUE THREAD

**Issue by bradwbradw** [720kb/angular-datepicker#129] opened 2015-12-16 19:40 UTC
When i use the datepicker as such:

```
        <datepicker date-format="mediumDate">
          <input type="date" id="date" name="date" required
                 ng-model="formData.date"/>
        </datepicker>
```

in the controller code, i initialize the date like so:

```
var todayDate = new Date();
formData.date = todayDate;
```

I go to the form, click on a day, but it does not set the day.  The picker text shows 'mm/dd/yyyy' and in the console there is a warning from jquery: `The specified value "Dec 25, 2015" does not conform to the required format, "yyyy-MM-dd".`

**Comment by 45kb** [comment] 2015-12-18 07:48
@bradwbradw Hi, can you send us a jsfiddle or plnkr, because i cannot reproduce this scenario.

Thanks

**Comment by 45kb** [comment] 2016-02-02 08:59
Unable to reproduce the scenario, closing.

Feel free to give more details and we will check it asap.

Thank you.

**Closed by 45kb** 2016-02-02 08:59 UTC
Labels: help wanted

**Comment by nisan92** [comment] 2017-03-05 09:16
I have the same issue , Please check https://jsfiddle.net/mhossain/waLpk14a/3/ 
for the scenario
thanks

**Comment by nisan92** [comment] 2017-03-05 09:33
Well i found the issue, this is happening only in Google chrome because of chrome default date and time format ....

**Comment by samuelt1** [comment] 2018-02-21 01:47
if you make it type text, then you will not get the nice HTML 5 date picker

**Comment by hmnshpj** [comment] 2018-04-05 06:03
Change the input type as text and use a class inside the input tag and in jquery use class instead of type.
You can refer the link below for more clarification: 

https://jsfiddle.net/breakerboyhimanshu/waLpk14a/76/
Ex.:
<form>
<input type="text" name="date" id="date" class="date" >
</form>

(function( $ ) {
	$('document') .ready( function(){

	$( '.date').datepicker({ dateFormat: 'dd-M-yy'});
  });
})( jQuery );
