### ISSUE TITLE
Live Demo doesn't work

### ISSUE THREAD

**Issue by xingped** [720kb/angular-datepicker#99] opened 2015-10-12 21:12 UTC
The live demo is stuck perpetually loading. It appears it cannot get a response for the following two requests:

http://yastatic.net/highlightjs/8.2/styles/vs.min.css
http://yandex.st/highlightjs/8.0/highlight.min.js

**Comment by wouldgo** [comment] 2015-10-12 22:41
Hi @xingped,
quite strange, I've fetched right now the page and alla seems to be retrieved.

Is it possible that the issue was temporary?

**Comment by wouldgo** [comment] 2015-10-13 06:56
Closing due the fact that I cannot reproduce this issue

**Closed by wouldgo** 2015-10-13 06:56 UTC

**Comment by xingped** [comment] 2015-10-13 15:15
Hm, still doesn't work for me, but only on my company's corporate network. Maybe they've blocked those CDNs for some reason. It's possible others might run into the same problem and you might consider manually including the files in your project.
